# Generated by Django 5.0.6 on 2024-06-22 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Flan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flan_uuid', models.UUIDField()),
                ('name', models.CharField(max_length=30)),
                ('description', models.TextField()),
                ('image_url', models.URLField(blank=True)),
                ('slug', models.SlugField()),
                ('js_private', models.BooleanField(default=False)),
            ],
        ),
    ]
