# Generated by Django 5.0.6 on 2024-06-22 21:36

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_alter_flan_flan_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flan',
            name='flan_uuid',
            field=models.UUIDField(default=uuid.uuid4),
        ),
        migrations.AlterField(
            model_name='flan',
            name='name',
            field=models.CharField(max_length=64),
        ),
    ]
