# Generated by Django 5.0.6 on 2024-07-02 14:18

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0006_cafe'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dulce',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dulce_uuid', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('name', models.CharField(max_length=64)),
                ('description', models.TextField()),
                ('image_url', models.URLField(blank=True)),
                ('slug', models.SlugField()),
                ('js_private', models.BooleanField(default=False)),
            ],
        ),
    ]
